### ISSUE TITLE
Add `wsk` to prerequisites in README

### ISSUE THREAD

**Issue by mlangbehn** [IBM/OpenWhisk-on-Kubernetes#10]
## Summary

`wsk` needs to be included as a prerequisite in [`README.md`][1].

[1]:https://raw.githubusercontent.com/IBM/OpenWhisk-on-Kubernetes/master/README.md

**Comment by mlangbehn** [comment]
Assigning @Tomcli per @animeshsingh's suggestion.

**Comment by animeshsingh** [comment]
Done - closing it.
