### ISSUE TITLE
FYI: A duplicate incubator project in Apache?

### ISSUE THREAD

**Issue by gyliu513** [IBM/OpenWhisk-on-Kubernetes#28]
Did you notice this project https://github.com/apache/incubator-openwhisk-deploy-kube ?

**Comment by mrutkows** [comment]
This Apache repo. should be the primary repo. IBM does its work for OW on Kube if possible as it is the official repo. IBM/Adobe/Red Hat are working together on (along with other companies and individuals).  Daniel Lavine is the IBMer who is leading our work here.

**Comment by gyliu513** [comment]
Thanks @mrutkows Did not quite catch what do you mean by `primary repo` and `official repo`, can you please elaborate more for this? :-)

**Comment by animeshsingh** [comment]
Hi @gyliu513 this repo in IBM org is primarily for running/testing openwhisk on IBM`s kubernetes offering, as mentioned here "This is an extension of the core OpenWhisk on Kubernetes deployment code"
 The repo in Apache should be your source for your work

**Comment by gyliu513** [comment]
Ah, I see, thanks @animeshsingh
