### ISSUE TITLE
Travis is broken

### ISSUE THREAD

**Issue by animeshsingh** [IBM/OpenWhisk-on-Kubernetes#3]
@Tomcli

**Comment by mlangbehn** [comment]
It looks like there have not been any builds yet for this repo. This may be because the integration was turned on after the last commit?

It should also be noted that the build status icon is incorrect in README.md. It is currently:

```markdown
[![Build Status](https://travis-ci.org/IBM/kubernetes-container-service-cassandra-deployment.svg?branch=master)](https://travis-ci.org/IBM/openwhisk-on-k8)
```

It should be:

```markdown
[![Build Status](https://travis-ci.org/IBM/OpenWhisk-on-Kubernetes.svg?branch=master)](https://travis-ci.org/IBM/OpenWhisk-on-Kubernetes)
```

**Comment by Tomcli** [comment]
This repository get renamed this week, right now I'm creating a pull request for the new changes in Travis and Bluemix button.

**Comment by animeshsingh** [comment]
Fixed - closing
