### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by animeshsingh** [IBM/OpenWhisk-on-Kubernetes#4]
@mlangbehn please get this tested

**Comment by mlangbehn** [comment]
@animeshsingh: Acknowledged.

**Comment by mlangbehn** [comment]
Related Issues:

* ~#6~ **CLOSED**
* ~#7~ **CLOSED**
* ~#8~ **CLOSED**
* ~#9~ **CLOSED** 
* ~#10~ **CLOSED** 
* ~#16~ **CLOSED**

**Comment by mlangbehn** [comment]
## Update

Testing complete with Bluemix, other than the issues opened with the documentation it seems to have worked. Please note that being new to OpenWhisk, I was not able to do much to verify that it is behaving as expected.

I found apache/incubator-openwhisk-deploy-kube#5 which looks like it will allow us to run IBM/OpenWhisk-on-Kubernetes in Minikube. I have an issue with my local installation of Virtualbox so I can not test tobias's patch yet.

**Comment by animeshsingh** [comment]
Thanks!

**Comment by mlangbehn** [comment]
## Update:

See IBM/OpenWhisk-on-Kubernetes#21 for information on Minikube in Travis CI.
