### ISSUE TITLE
Fix links in Markdown files

### ISSUE THREAD

**Issue by mlangbehn** [IBM/OpenWhisk-on-Kubernetes#6]
## Summary

Several links in [`README.md`][1] and [`CONTRIBUTING.md`][2] point to the wrong or, in some cases, non-existent locations.

## Specific Issues

*NOTE: issues are listed in the order they appear in the files.*

### README

* Travis build status icon

    ```markdown
    [![Build Status](https://travis-ci.org/IBM/kubernetes-container-service-cassandra-deployment.svg?branch=master)](https://travis-ci.org/IBM/openwhisk-on-k8)
    ```

    Should be:

    ```markdown
    [![Build Status](https://travis-ci.org/IBM/OpenWhisk-on-Kubernetes.svg?branch=master)](https://travis-ci.org/IBM/OpenWhisk-on-Kubernetes)
    ```

* Step 5

    ```markdown
    [Step 5](#5-using-cql)
    ```

    Does not link to anything. Should this be?:

    ```markdown
    step 5 in [manually deploying](#manually-deploying)
    ```

    This is also the case under step 4.

* Prerequisites

    ```markdown
        ```Note: Use the following link to complete the instructions at the bottom
        https://github.com/openwhisk/openwhisk-devtools/tree/master/kubernetes
        ```
    ```

    Renders as:

    ```Note: Use the following link to complete the instructions at the bottom
    https://github.com/openwhisk/openwhisk-devtools/tree/master/kubernetes
    ```

    This is also a dead-link.

* Step 1

    ```markdown
    [Download OpenWhisk-Kubernetes codebase](#1-download-openWhisk-kubernetes-codebase)
    ````

    Should be:

    ```markdown
    [Download OpenWhisk-Kubernetes codebase](#1-download-openwhisk-kubernetes-codebase)
    ```

    `openWhisk` should also be `openwhisk` in step two.

* Troubleshooting

    ```markdown
    #### [Troubleshooting](#troubleshooting)
    ```

    Is self-referencing. This is also an issue under step 6. Please either remove the h4 tag for troubleshooting here, or link it to `#troubleshooting-1`.

* Step 3

    ```markdown
    `git clone https://github.com/IBM/openwhisk-on-k8.git`
    ```

    Should be:

    ```markdown
    `git clone https://github.com/IBM/OpenWhisk-on-Kubernetes.git`
    ```

* Step 4

    ```markdown
    [here](ansible-kube/environments/kube/files)
    ```

    Is a dead-link (does this directory exist in a different repository?).

* Step 5; sub-step 2

    ```markdown
    [OpenWhisk](https://github.com/openwhisk/openwhisk)
    ```

    Should be:

    ```markdown
    [OpenWhisk](https://github.com/apache/incubator-openwhisk)
    ```

* configure_whisk.yml

    ```markdown
    [configure_whisk.yml](configure/configure_whisk.yml)
    ```

    Is a dead-link (does this directory exist in a different repository?). This is also found under step 6.

* nginx

    ```markdown
    [nginx](ansible-kube/environments/kube/files/nginx.yml)
    ```

    Is a dead-link (does this directory exist in a different repository?).

### CONTRIBUTING

* Repo link:

    ```markdown
    [GitHub repository](https://github.com/IBM/ogs-serverless-apis)
    ```

    Should be:

    ```markdown
    [GitHub repository](https://github.com/IBM/OpenWhisk-on-Kubernetes)
    ```

* Issue tracker:

    ```markdown
    [issue tracker](https://github.com/IBM/ogs-serverless-apis/issues)
    ```

    Should be:

    ```markdown
    [issue tracker](https://github.com/IBM/OpenWhisk-on-Kubernetes/issues)
    ```

    This is also the case in the `Preposing new features` and `Fixing bugs` subsections.

[1]:https://raw.githubusercontent.com/IBM/OpenWhisk-on-Kubernetes/master/README.md
[2]:https://raw.githubusercontent.com/IBM/OpenWhisk-on-Kubernetes/master/CONTRIBUTING.md

**Comment by mlangbehn** [comment]
Assigning @Tomcli per @animeshsingh's suggestion.

**Comment by Tomcli** [comment]
Thank for your advice, fixed in #5.

**Comment by mlangbehn** [comment]
@Tomcli: One more quick change.

```shell
git clone https://github.com/IBM/OpenWhisk-on-Kubernetes.git.git
```

Should be:

```shell
git clone https://github.com/IBM/OpenWhisk-on-Kubernetes.git
```

**Comment by animeshsingh** [comment]
Fixed - closing
