### ISSUE TITLE
Fix various misspellings and grammatical issues in README.md 

### ISSUE THREAD

**Issue by mlangbehn** [IBM/OpenWhisk-on-Kubernetes#7]
## Summary

Various spelling and grammatical issues exist [`README.md`][1].

[1]:https://raw.githubusercontent.com/IBM/OpenWhisk-on-Kubernetes/master/README.md

**Comment by mlangbehn** [comment]
Assigning @Tomcli per @animeshsingh's suggestion.

**Comment by animeshsingh** [comment]
Closing this based on @Tomcli` comment - if something specific doesn`t look right, we can point to it in another issue
