### ISSUE TITLE
Simplify commands in README

### ISSUE THREAD

**Issue by mlangbehn** [IBM/OpenWhisk-on-Kubernetes#8]
## Summary

One line commands using `grep`, `awk`, and `cut` in [`README.md`][1] can be simplified to run one utility.

[1]:https://raw.githubusercontent.com/IBM/OpenWhisk-on-Kubernetes/master/README.md

**Comment by mlangbehn** [comment]
Assigning @Tomcli per @animeshsingh's suggestion.

**Comment by Tomcli** [comment]
@mlangbehn Sorry I'm confused. What do you mean by one utility?

**Comment by mlangbehn** [comment]
@Tomcli: in this issue I'm suggesting where possible, we simplify our commands by using less to accomplish a task. For example, `awk` is able to handle searching, formatting, and printing, so we could change:

```shell
export AUTH_SECRET=$(kubectl -n openwhisk get secret openwhisk-auth-tokens -o yaml | grep 'auth_whisk_system:' | awk '{print $2}' | base64 --decode)
```

into:

```shell
export AUTH_SECRET=$(kubectl -n openwhisk get secret openwhisk-auth-tokens -o yaml | awk ' /auth_whisk_system/ {print $2}' | base64 --decode)
```

**Comment by mlangbehn** [comment]
Issue resolved. Closing accordingly.
