### ISSUE TITLE
Add command to set kube_node_ip

### ISSUE THREAD

**Issue by mlangbehn** [IBM/OpenWhisk-on-Kubernetes#9]
## Summary

A command should be added to [`README.md`][1] to export `KUBE_NODE_IP`.

## Explanation

Currently, the instructions to configure `wsk` show:

```markdown
wsk property set --auth $AUTH_SECRET --apihost https://[kube_node_ip]:$WSK_PORT
```

`kube_node_ip` is nondescript, and could be set in a similar way to `$AUTH_SECRET` and `$WSK_PORT`. Please see issue #8 for request to simplify commands.

[1]:https://raw.githubusercontent.com/IBM/OpenWhisk-on-Kubernetes/master/README.md

**Comment by mlangbehn** [comment]
Assigning @Tomcli per @animeshsingh's suggestion.

**Comment by animeshsingh** [comment]
Done - closing it
